#!/usr/bin/env bash

source /root/ovirt-backup/etc/backups/functions
source /root/ovirt-backup/bin/activate

mkdir -p ${LOGDIR}
touch ${BACKUP_LOGFILE}

if [ "$DEBUG" -ne 0 ]
then
    ( set -o posix; set )
fi

for host in $( niet -f newline ".backup.daily" ${BACKUP_FILE} )
do
    if [ "$RUN_BACKUPS" -eq 0 ]
    then
        echo "Backups disabled"
    else
        echo "Backing up ${host}" 2>&1 >${BACKUP_LOGFILE}
        ${ROOTDIR}/backup_vm.py -ddd --hostname ${host} 2>&1 >${BACKUP_LOGFILE}
        echo "Finishing backup of ${host}" 2>&1 >${BACKUP_LOGFILE}
    fi

    pushd ${BACKUP_DIR}/${host} 2>&1 >/dev/null
    echo "Deleting file $( ls -tDp | awk 'NR>5' ) from ${BACKUP_DIR}/${host}..."
    ls -tDp | awk 'NR>5' | xargs --no-run-if-empty rm -rf {} && 
    popd 2>&1 >/dev/null
done
ls 