#!/usr/bin/env bash
#
# Backup File 
#

ROOTDIR=/root/ovirt-backup
HOSTNAME=$( hostname -s )
ETCDIR=${ROOTDIR}/etc
LOGDIR=${ROOTDIR}/log
BACKUP_LOGFILE="${LOGDIR}/${HOSTNAME}.log"
BACKUP_FILE="${ETCDIR}/${HOSTNAME}.yml"
RUN_BACKUPS=1
DEBUG=0

function run_backup()
{
    if [ "$RUN_BACKUPS" -eq 0 ]
    then
        echo "Backups disabled"
    fi

    source ${ROOTDIR}/bin/activate

    ${ROOTDIR}/backup_vm.py $@ 
}

